# Alans Spotify extended data
Data exploration

## Creating extended audio streaming table

In [81]:
import pandas as pd
from pathlib import Path
import os

FOLDER = Path('/Users/qaulanmaruf/Desktop/alans_spotify_2025/spotify_account_data/streaming_extended')
extended_audio_stream_table = []

for file in FOLDER.glob('Streaming_History_Audio*'):
    extended_audio_stream_table.append(pd.read_json(file))

extended_audio_stream_table = pd.concat(extended_audio_stream_table, ignore_index=True)
extended_audio_stream_table = extended_audio_stream_table.drop(columns=["ip_addr"])

In [82]:
from IPython.display import display

display(extended_audio_stream_table.head(10))

,ts,platform,ms_played,conn_country,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,episode_name,episode_show_name,...,audiobook_uri,audiobook_chapter_uri,audiobook_chapter_title,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode
0,2024-06-23T08:43:16Z,ios,188000,ID,Terang Bulan,Rosy & Andres,Pasar Malam Souvenirs,spotify:track:0h77cZ1FBsqHrkN5zX2tnZ,NaN,NaN,...,NaN,NaN,NaN,trackdone,trackdone,False,False,False,1.719132e+09,False
1,2024-06-23T08:44:37Z,ios,79546,ID,Make Me an Island (Original 1969 Recording),Joe Dolan,Legends of Irish Music: Joe Dolan,spotify:track:6DfuJvyNjF5gdfYpHUJOVk,NaN,NaN,...,NaN,NaN,NaN,trackdone,fwdbtn,False,True,False,1.719132e+09,False
2,2024-06-23T08:44:38Z,ios,1020,ID,Storybook Children,Sandra & Andres,Happy Together,spotify:track:6Oj9rdb4w4Ei9VwY9bFJTZ,NaN,NaN,...,NaN,NaN,NaN,fwdbtn,fwdbtn,False,True,False,1.719132e+09,False
3,2024-06-23T08:44:40Z,ios,2090,ID,"Beg, Steal Or Borrow",The New Seekers,The Albums 1970-73,spotify:track:0oIL0V8acWjmUDs79Uiqsz,NaN,NaN,...,NaN,NaN,NaN,fwdbtn,backbtn,False,True,False,1.719132e+09,False
4,2024-06-23T08:44:43Z,ios,2500,ID,Storybook Children,Sandra & Andres,Happy Together,spotify:track:6Oj9rdb4w4Ei9VwY9bFJTZ,NaN,NaN,...,NaN,NaN,NaN,backbtn,fwdbtn,False,True,False,1.719132e+09,False
5,2024-06-23T08:44:43Z,ios,540,ID,"Beg, Steal Or Borrow",The New Seekers,The Albums 1970-73,spotify:track:0oIL0V8acWjmUDs79Uiqsz,NaN,NaN,...,NaN,NaN,NaN,fwdbtn,fwdbtn,False,True,False,1.719132e+09,False
6,2024-06-23T08:44:55Z,ios,11430,ID,Somewhere Between,Tumbleweeds,Tumbleweeds,spotify:track:4yaUH3iE9siIBrv5GfDe6G,NaN,NaN,...,NaN,NaN,NaN,fwdbtn,fwdbtn,False,True,False,1.719132e+09,False
7,2024-06-23T08:44:57Z,ios,1860,ID,Please Help Me I'm Falling,Rosy & Andres,My Love,spotify:track:7HVMgbUfRlMoy05OqN4eRp,NaN,NaN,...,NaN,NaN,NaN,fwdbtn,fwdbtn,False,True,False,1.719132e+09,False
8,2024-06-23T08:45:00Z,ios,3300,ID,I'm Leaving It (All) Up To You,Donny Osmond,Love Songs,spotify:track:5hyd2fifGiazSiiSxvPYoS,NaN,NaN,...,NaN,NaN,NaN,fwdbtn,fwdbtn,False,True,False,1.719132e+09,False
9,2024-06-23T08:45:01Z,ios,1210,ID,Kiss Me Kiss Your Baby,Brotherhood of Man,The Best Of,spotify:track:2GqjIWOmPx7xMbrx2Qm8je,NaN,NaN,...,NaN,NaN,NaN,fwdbtn,fwdbtn,False,True,False,1.719132e+09,False

In [83]:
print(extended_audio_stream_table.info())

<class 'pandas.DataFrame'>
RangeIndex: 246248 entries, 0 to 246247
Data columns (total 22 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   ts                                 246248 non-null  str
 1   platform                           246248 non-null  str
 2   ms_played                          246248 non-null  int64
 3   conn_country                       246231 non-null  str
 4   master_metadata_track_name         246160 non-null  str
 5   master_metadata_album_artist_name  246160 non-null  str
 6   master_metadata_album_album_name   246160 non-null  str
 7   spotify_track_uri                  246160 non-null  str
 8   episode_name                       88 non-null      object
 9   episode_show_name                  88 non-null      object
 10  spotify_episode_uri                88 non-null      object
 11  audiobook_title                    0 non-null       float64
 12  audiobook_uri                      0 non-null       float64
 13  audiobook_chapter_uri              0 non-null       float64
 14  audiobook_chapter_title            0 non-null       float64
 15  reason_start                       246248 non-null  str
 16  reason_end                         246248 non-null  str
 17  shuffle                            246248 non-null  bool
 18  skipped                            246248 non-null  bool
 19  offline                            246248 non-null  bool
 20  offline_timestamp                  109028 non-null  float64
 21  incognito_mode                     246248 non-null  bool
dtypes: bool(4), float64(5), int64(1), object(3), str(9)
memory usage: 34.8+ MB
None

## Extended video streaming table

In [84]:
extended_video_stream_table = pd.read_json(FOLDER / "Streaming_History_Video_2022-2026.json")
extended_video_stream_table = extended_video_stream_table.drop(columns=["ip_addr"])

In [85]:
display(extended_video_stream_table.head(10))

,ts,platform,ms_played,conn_country,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,episode_name,episode_show_name,...,audiobook_uri,audiobook_chapter_uri,audiobook_chapter_title,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode
0,2022-11-30T15:35:31Z,ios,0,NL,Terluka Menginginkanmu,Mark Natama,Terluka Menginginkanmu,spotify:track:1zjMCWzhuZbloa3BtPEpIs,NaN,NaN,...,NaN,NaN,NaN,unknown,endplay,False,True,NaN,NaN,True
1,2022-11-30T15:35:31Z,ios,8429,NL,Terluka Menginginkanmu,Mark Natama,Terluka Menginginkanmu,spotify:track:1zjMCWzhuZbloa3BtPEpIs,NaN,NaN,...,NaN,NaN,NaN,unknown,endplay,False,True,NaN,NaN,True
2,2022-11-30T15:35:39Z,ios,8572,NL,Pesona,Lomba Sihir,"Pesona - Sounds Cute, Might Delete Later (Dese...",spotify:track:1H77vkVDbs59KNk97Z7r2s,NaN,NaN,...,NaN,NaN,NaN,unknown,endplay,False,True,NaN,NaN,True
3,2022-11-30T15:35:39Z,ios,0,NL,Pesona,Lomba Sihir,"Pesona - Sounds Cute, Might Delete Later (Dese...",spotify:track:1H77vkVDbs59KNk97Z7r2s,NaN,NaN,...,NaN,NaN,NaN,unknown,endplay,False,True,NaN,NaN,True
4,2022-11-30T15:35:39Z,ios,0,NL,Terluka Menginginkanmu,Mark Natama,Terluka Menginginkanmu,spotify:track:1zjMCWzhuZbloa3BtPEpIs,NaN,NaN,...,NaN,NaN,NaN,unknown,endplay,False,True,NaN,NaN,True
5,2022-11-30T15:35:42Z,ios,0,NL,AKU MASIH MEMIKIRKANMU,Kezia,AKU MASIH MEMIKIRKANMU,spotify:track:2KCikMsmJSBEgfOOskQ87P,NaN,NaN,...,NaN,NaN,NaN,unknown,endplay,False,True,NaN,NaN,True
6,2022-11-30T15:35:42Z,ios,0,NL,Pesona,Lomba Sihir,"Pesona - Sounds Cute, Might Delete Later (Dese...",spotify:track:1H77vkVDbs59KNk97Z7r2s,NaN,NaN,...,NaN,NaN,NaN,unknown,endplay,False,True,NaN,NaN,True
7,2022-11-30T15:35:42Z,ios,2200,NL,Bila Kemarin,Yotari,Bila Kemarin,spotify:track:50CsVpRhz7dhFPUWZs4rhS,NaN,NaN,...,NaN,NaN,NaN,unknown,endplay,False,True,NaN,NaN,True
8,2023-07-21T03:23:42Z,ios,4364,ID,Mereguk Anti Depresan Lagi,The Jansen,Banal Semakin Binal,spotify:track:3tfe3JifqPcOYE52NVBcmN,NaN,NaN,...,NaN,NaN,NaN,unknown,endplay,False,True,NaN,NaN,False
9,2023-07-21T03:23:46Z,ios,3823,ID,God Save The Queen,Sex Pistols,"Never Mind The Bollocks, Here’s The Sex Pistols",spotify:track:2mHchPRtQWet3iIS3jANr1,NaN,NaN,...,NaN,NaN,NaN,unknown,endplay,False,True,NaN,NaN,False

In [86]:
print(extended_video_stream_table.info())

<class 'pandas.DataFrame'>
RangeIndex: 867 entries, 0 to 866
Data columns (total 22 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   ts                                 867 non-null    str
 1   platform                           867 non-null    str
 2   ms_played                          867 non-null    int64
 3   conn_country                       867 non-null    str
 4   master_metadata_track_name         615 non-null    str
 5   master_metadata_album_artist_name  615 non-null    str
 6   master_metadata_album_album_name   615 non-null    str
 7   spotify_track_uri                  615 non-null    str
 8   episode_name                       252 non-null    str
 9   episode_show_name                  252 non-null    str
 10  spotify_episode_uri                252 non-null    str
 11  audiobook_title                    0 non-null      float64
 12  audiobook_uri                      0 non-null      float64
 13  audiobook_chapter_uri              0 non-null      float64
 14  audiobook_chapter_title            0 non-null      float64
 15  reason_start                       867 non-null    str
 16  reason_end                         867 non-null    str
 17  shuffle                            867 non-null    bool
 18  skipped                            867 non-null    bool
 19  offline                            774 non-null    float64
 20  offline_timestamp                  774 non-null    float64
 21  incognito_mode                     867 non-null    bool
dtypes: bool(3), float64(6), int64(1), str(12)
memory usage: 131.4 KB
None

## Appending both tables as one
Assuming that video tables is part of streamed instances

In [88]:
extended_stream_table = pd.concat([extended_audio_stream_table, extended_video_stream_table], ignore_index=True)

## Data validation
Exploring table feature using SQL

In [60]:
from pandasql import sqldf

psql = lambda q: sqldf(q, globals())

In [89]:
# min max ms_played

query = """ 
    select 
        min(ms_played) min_ms_played
        , max(ms_played) max_ms_played
    from(
        select distinct 
            ms_played 
        from 
            extended_stream_table
    )
    ;
"""

print(psql(query))

   min_ms_played  max_ms_played
0              0        2911421

In [78]:
# query = """ 
#     select distinct reason_start from extended_stream;
# """

query = """ 
    select distinct reason_end from extended_stream_table;
"""

print(psql(query))

                      reason_end
0                      trackdone
1                         fwdbtn
2                        backbtn
3                        endplay
4   unexpected-exit-while-paused
5                         remote
6                         logout
7                     trackerror
8                        unknown
9                unexpected-exit
10                      clickrow

In [79]:
# FINAL QUERY

query = """ 
    select * from (
        select 
            ts
            , ms_played
            , master_metadata_track_name
            , master_metadata_album_album_name
            , master_metadata_album_artist_name
            , skipped
        from 
            extended_stream_table 
        where skipped = 1
    )
    where ms_played <> 0
    ;
"""

df = psql(query)

display(df.head(10))

# meaning need to filter out instances where songs are skipped

,ts,ms_played,master_metadata_track_name,master_metadata_album_album_name,master_metadata_album_artist_name,skipped
0,2024-06-23T08:44:37Z,79546,Make Me an Island (Original 1969 Recording),Legends of Irish Music: Joe Dolan,Joe Dolan,1
1,2024-06-23T08:44:38Z,1020,Storybook Children,Happy Together,Sandra & Andres,1
2,2024-06-23T08:44:40Z,2090,"Beg, Steal Or Borrow",The Albums 1970-73,The New Seekers,1
3,2024-06-23T08:44:43Z,2500,Storybook Children,Happy Together,Sandra & Andres,1
4,2024-06-23T08:44:43Z,540,"Beg, Steal Or Borrow",The Albums 1970-73,The New Seekers,1
5,2024-06-23T08:44:55Z,11430,Somewhere Between,Tumbleweeds,Tumbleweeds,1
6,2024-06-23T08:44:57Z,1860,Please Help Me I'm Falling,My Love,Rosy & Andres,1
7,2024-06-23T08:45:00Z,3300,I'm Leaving It (All) Up To You,Love Songs,Donny Osmond,1
8,2024-06-23T08:45:01Z,1210,Kiss Me Kiss Your Baby,The Best Of,Brotherhood of Man,1
9,2024-06-23T08:45:03Z,1550,We Gotta Stop,Back in Time,Liliane Saint-Pierre,1

In [98]:
query = """  
    select 
        ts timestamp
        , DATE(ts, '+7 hours') AS date
        , STRFTIME('%H:%M', ts, '+7 hours') AS time_hm
        , STRFTIME('%H', ts, '+7 hours') AS time_h
        , ms_played
        , ms_played / 1000 as sec_played
        , ms_played / 60000 as min_played
        , platform
        , conn_country
        , master_metadata_track_name
        , master_metadata_album_artist_name
        , master_metadata_album_album_name
        , spotify_track_uri
        , episode_name
        , episode_show_name
        , spotify_episode_uri
        , audiobook_title
        , audiobook_uri
        , audiobook_chapter_uri
        , audiobook_chapter_title
        , reason_start
        , reason_end
        , shuffle
        , skipped
        , offline
        , datetime(offline_timestamp, 'unixepoch', '+7 hours') offline_timestamp
        , STRFTIME('%H:%M', datetime(offline_timestamp, 'unixepoch', '+7 hours')) AS offline_time_hm
        , STRFTIME('%H', datetime(offline_timestamp, 'unixepoch', '+7 hours')) AS offline_time_h
        , incognito_mode
    from 
        extended_stream_table
    where skipped = 0
"""

# df = ssot()

# df = df.create_extended_stream_table

# df = psql(query)
# display(df.head(10))

print(psql(query))

                   timestamp        date time_hm time_h  ms_played  \
0       2024-06-23T08:43:16Z  2024-06-23   15:43     15     188000
1       2024-06-23T08:47:16Z  2024-06-23   15:47     15     130000
2       2024-06-23T08:53:35Z  2024-06-23   15:53     15     218000
3       2024-06-23T08:59:15Z  2024-06-23   15:59     15     211052
4       2024-06-23T09:01:42Z  2024-06-23   16:01     16     146333
...                      ...         ...     ...    ...        ...
195817  2026-03-24T09:59:15Z  2026-03-24   16:59     16     353688
195818  2026-03-24T10:06:26Z  2026-03-24   17:06     17     156466
195819  2026-03-24T10:13:25Z  2026-03-24   17:13     17     187341
195820  2026-03-24T10:16:23Z  2026-03-24   17:16     17     177223
195821  2026-03-24T10:23:56Z  2026-03-24   17:23     17     240421

        sec_played  min_played platform conn_country  \
0              188           3      ios           ID
1              130           2      ios           ID
2              218           3      ios           ID
3              211           3      ios           ID
4              146           2      ios           ID
...            ...         ...      ...          ...
195817         353           5      ios           SG
195818         156           2      ios           SG
195819         187           3      ios           SG
195820         177           2      ios           SG
195821         240           4      ios           SG

                               master_metadata_track_name  ...  \
0                                            Terang Bulan  ...
1                                        Ajun, Ajun, Ajun  ...
2                                  Vaarwel N'n Dromenland  ...
3                              I'm Still in Love with You  ...
4                               In The Still of the Night  ...
...                                                   ...  ...
195817     Everybody's Changing - Live AOL Session / 2004  ...
195818              I Have A Dream - from ABBA In Concert  ...
195819  I Do, I Do, I Do, I Do, I Do - Live - ABBA Dow...  ...
195820                 Ring Ring - Live - ABBA Down Under  ...
195821  Somewhere Only We Know - Live At The Hub, Roun...  ...

       audiobook_chapter_title reason_start reason_end shuffle skipped  \
0                         None    trackdone  trackdone       0       0
1                         None       fwdbtn  trackdone       0       0
2                         None       fwdbtn  trackdone       0       0
3                         None       fwdbtn  trackdone       0       0
4                         None    trackdone  trackdone       0       0
...                        ...          ...        ...     ...     ...
195817                    None     clickrow  trackdone       0       0
195818                    None     clickrow  trackdone       0       0
195819                    None       fwdbtn  trackdone       0       0
195820                    None    trackdone  trackdone       0       0
195821                    None     clickrow  trackdone       0       0

       offline    offline_timestamp offline_time_hm offline_time_h  \
0            0  2024-06-23 15:40:08           15:40             15
1            0  2024-06-23 15:45:07           15:45             15
2            0  2024-06-23 15:49:57           15:49             15
3            0  2024-06-23 15:54:56           15:54             15
4            0  2024-06-23 15:59:15           15:59             15
...        ...                  ...             ...            ...
195817     0.0  2026-03-24 16:53:20           16:53             16
195818     0.0  2026-03-24 17:03:50           17:03             17
195819     0.0  2026-03-24 17:10:17           17:10             17
195820     0.0  2026-03-24 17:13:26           17:13             17
195821     0.0  2026-03-24 17:19:55           17:19             17

       incognito_mode
0                   0
1                   0
2                   0
3                   0
4                   0
...               ...
195817              0
195818              0
195819              0
195820              0
195821              0

[195822 rows x 29 columns]

In [101]:
query = """ 
select distinct
    master_metadata_track_name
    , master_metadata_album_artist_name
    , master_metadata_album_artist_name
from 
    extended_stream_table
where skipped = 0
"""

print(psql(query))

                              master_metadata_track_name  \
0                                           Terang Bulan
1                                       Ajun, Ajun, Ajun
2                                 Vaarwel N'n Dromenland
3                             I'm Still in Love with You
4                              In The Still of the Night
...                                                  ...
14315     Everybody's Changing - Live AOL Session / 2004
14316  Somewhere Only We Know - Live At The Hub, Roun...
14317              I Have A Dream - from ABBA In Concert
14318  I Do, I Do, I Do, I Do, I Do - Live - ABBA Dow...
14319                 Ring Ring - Live - ABBA Down Under

      master_metadata_album_artist_name master_metadata_album_artist_name
0                         Rosy & Andres                     Rosy & Andres
1                         Rosy & Andres                     Rosy & Andres
2                         Rosy & Andres                     Rosy & Andres
3                          Oscar Harris                      Oscar Harris
4                           Jack Jersey                       Jack Jersey
...                                 ...                               ...
14315                             Keane                             Keane
14316                             Keane                             Keane
14317                              ABBA                              ABBA
14318                              ABBA                              ABBA
14319                              ABBA                              ABBA

[14320 rows x 3 columns]