In [5]:
import pandas as pd
from pathlib import Path
import os

FOLDER = Path('/Users/qaulanmaruf/Desktop/alans_spotify_2025/spotify_account_data/streaming_extended')
audio_stream_extended = []

for file in FOLDER.glob('Streaming_History_Audio*'):
    audio_stream_extended.append(pd.read_json(file))

audio_stream_extended = pd.concat(audio_stream_extended, ignore_index=True)

In [6]:
from IPython.display import display

display(audio_stream_extended.head(10))

,ts,platform,ms_played,conn_country,ip_addr,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,episode_name,...,audiobook_uri,audiobook_chapter_uri,audiobook_chapter_title,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode
0,2024-06-23T08:43:16Z,ios,188000,ID,182.2.137.77,Terang Bulan,Rosy & Andres,Pasar Malam Souvenirs,spotify:track:0h77cZ1FBsqHrkN5zX2tnZ,NaN,...,NaN,NaN,NaN,trackdone,trackdone,False,False,False,1.719132e+09,False
1,2024-06-23T08:44:37Z,ios,79546,ID,182.2.137.77,Make Me an Island (Original 1969 Recording),Joe Dolan,Legends of Irish Music: Joe Dolan,spotify:track:6DfuJvyNjF5gdfYpHUJOVk,NaN,...,NaN,NaN,NaN,trackdone,fwdbtn,False,True,False,1.719132e+09,False
2,2024-06-23T08:44:38Z,ios,1020,ID,182.2.137.77,Storybook Children,Sandra & Andres,Happy Together,spotify:track:6Oj9rdb4w4Ei9VwY9bFJTZ,NaN,...,NaN,NaN,NaN,fwdbtn,fwdbtn,False,True,False,1.719132e+09,False
3,2024-06-23T08:44:40Z,ios,2090,ID,182.2.137.77,"Beg, Steal Or Borrow",The New Seekers,The Albums 1970-73,spotify:track:0oIL0V8acWjmUDs79Uiqsz,NaN,...,NaN,NaN,NaN,fwdbtn,backbtn,False,True,False,1.719132e+09,False
4,2024-06-23T08:44:43Z,ios,2500,ID,182.2.137.77,Storybook Children,Sandra & Andres,Happy Together,spotify:track:6Oj9rdb4w4Ei9VwY9bFJTZ,NaN,...,NaN,NaN,NaN,backbtn,fwdbtn,False,True,False,1.719132e+09,False
5,2024-06-23T08:44:43Z,ios,540,ID,182.2.137.77,"Beg, Steal Or Borrow",The New Seekers,The Albums 1970-73,spotify:track:0oIL0V8acWjmUDs79Uiqsz,NaN,...,NaN,NaN,NaN,fwdbtn,fwdbtn,False,True,False,1.719132e+09,False
6,2024-06-23T08:44:55Z,ios,11430,ID,182.2.137.77,Somewhere Between,Tumbleweeds,Tumbleweeds,spotify:track:4yaUH3iE9siIBrv5GfDe6G,NaN,...,NaN,NaN,NaN,fwdbtn,fwdbtn,False,True,False,1.719132e+09,False
7,2024-06-23T08:44:57Z,ios,1860,ID,182.2.137.77,Please Help Me I'm Falling,Rosy & Andres,My Love,spotify:track:7HVMgbUfRlMoy05OqN4eRp,NaN,...,NaN,NaN,NaN,fwdbtn,fwdbtn,False,True,False,1.719132e+09,False
8,2024-06-23T08:45:00Z,ios,3300,ID,182.2.137.77,I'm Leaving It (All) Up To You,Donny Osmond,Love Songs,spotify:track:5hyd2fifGiazSiiSxvPYoS,NaN,...,NaN,NaN,NaN,fwdbtn,fwdbtn,False,True,False,1.719132e+09,False
9,2024-06-23T08:45:01Z,ios,1210,ID,182.2.137.77,Kiss Me Kiss Your Baby,Brotherhood of Man,The Best Of,spotify:track:2GqjIWOmPx7xMbrx2Qm8je,NaN,...,NaN,NaN,NaN,fwdbtn,fwdbtn,False,True,False,1.719132e+09,False

In [7]:
audio_stream_extended = pd.read_json(FOLDER / "Streaming_History_Video_2022-2026.json")

In [8]:
display(audio_stream_extended.head(10))

,ts,platform,ms_played,conn_country,ip_addr,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,episode_name,...,audiobook_uri,audiobook_chapter_uri,audiobook_chapter_title,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode
0,2022-11-30T15:35:31Z,ios,0,NL,144.178.95.154,Terluka Menginginkanmu,Mark Natama,Terluka Menginginkanmu,spotify:track:1zjMCWzhuZbloa3BtPEpIs,NaN,...,NaN,NaN,NaN,unknown,endplay,False,True,NaN,NaN,True
1,2022-11-30T15:35:31Z,ios,8429,NL,144.178.95.154,Terluka Menginginkanmu,Mark Natama,Terluka Menginginkanmu,spotify:track:1zjMCWzhuZbloa3BtPEpIs,NaN,...,NaN,NaN,NaN,unknown,endplay,False,True,NaN,NaN,True
2,2022-11-30T15:35:39Z,ios,8572,NL,144.178.95.154,Pesona,Lomba Sihir,"Pesona - Sounds Cute, Might Delete Later (Dese...",spotify:track:1H77vkVDbs59KNk97Z7r2s,NaN,...,NaN,NaN,NaN,unknown,endplay,False,True,NaN,NaN,True
3,2022-11-30T15:35:39Z,ios,0,NL,144.178.95.154,Pesona,Lomba Sihir,"Pesona - Sounds Cute, Might Delete Later (Dese...",spotify:track:1H77vkVDbs59KNk97Z7r2s,NaN,...,NaN,NaN,NaN,unknown,endplay,False,True,NaN,NaN,True
4,2022-11-30T15:35:39Z,ios,0,NL,144.178.95.154,Terluka Menginginkanmu,Mark Natama,Terluka Menginginkanmu,spotify:track:1zjMCWzhuZbloa3BtPEpIs,NaN,...,NaN,NaN,NaN,unknown,endplay,False,True,NaN,NaN,True
5,2022-11-30T15:35:42Z,ios,0,NL,144.178.95.154,AKU MASIH MEMIKIRKANMU,Kezia,AKU MASIH MEMIKIRKANMU,spotify:track:2KCikMsmJSBEgfOOskQ87P,NaN,...,NaN,NaN,NaN,unknown,endplay,False,True,NaN,NaN,True
6,2022-11-30T15:35:42Z,ios,0,NL,144.178.95.154,Pesona,Lomba Sihir,"Pesona - Sounds Cute, Might Delete Later (Dese...",spotify:track:1H77vkVDbs59KNk97Z7r2s,NaN,...,NaN,NaN,NaN,unknown,endplay,False,True,NaN,NaN,True
7,2022-11-30T15:35:42Z,ios,2200,NL,144.178.95.154,Bila Kemarin,Yotari,Bila Kemarin,spotify:track:50CsVpRhz7dhFPUWZs4rhS,NaN,...,NaN,NaN,NaN,unknown,endplay,False,True,NaN,NaN,True
8,2023-07-21T03:23:42Z,ios,4364,ID,182.3.43.98,Mereguk Anti Depresan Lagi,The Jansen,Banal Semakin Binal,spotify:track:3tfe3JifqPcOYE52NVBcmN,NaN,...,NaN,NaN,NaN,unknown,endplay,False,True,NaN,NaN,False
9,2023-07-21T03:23:46Z,ios,3823,ID,182.3.43.98,God Save The Queen,Sex Pistols,"Never Mind The Bollocks, Here’s The Sex Pistols",spotify:track:2mHchPRtQWet3iIS3jANr1,NaN,...,NaN,NaN,NaN,unknown,endplay,False,True,NaN,NaN,False