# Alan's spotify 2025
Exploring my Spotify data

# Creating streaming table

In [18]:
import pandas as pd
from pathlib import Path
import os

FOLDER_STREAM = Path('/Users/qaulanmaruf/Desktop/alans_spotify_2025/spotify_account_data/streaming')
stream_table = []

for file in FOLDER_STREAM.glob('StreamingHistory_music*'):
    stream_table.append(pd.read_json(file))

stream_table = pd.concat(stream_table, ignore_index=True)

In [19]:
from IPython.display import display

display(stream_table.head(10))

,endTime,artistName,trackName,msPlayed
0,2025-07-18 10:39,Dewi - Dewi,Dokter Cinta,235333
1,2025-07-18 10:45,Cinta Laura Kiehl,Oh Baby,267986
2,2025-07-18 10:46,Aura Kasih,Mari Bercinta,15630
3,2025-07-18 15:48,Mulan Jameela,Abracadabra,37380
4,2025-07-18 15:51,John West,Ome Jan,154787
5,2025-07-18 15:55,Deborah Hanna,Takkan Berpaling DariMu,2140
6,2025-07-18 15:55,Freddie Mercury,I Was Born To Love You - Special Edition,219306
7,2025-07-18 15:55,Seventeen,Tanpa Pesan Terakhir,2570
8,2025-07-18 15:55,Kerispatih,Mengenangmu,14386
9,2025-07-18 15:56,Muse,Thoughts of a Dying Atheist (Recorded Live at ...,4700

In [20]:
from pandasql import sqldf

psql = lambda q: sqldf(q, globals())

In [21]:
query = """ 
    select
        endTime end_ts
        , DATE(endTime, '+7 hours') AS end_date
        , STRFTIME('%H:%M', endTime, '+7 hours') AS end_time_hm
        , STRFTIME('%H', endTime, '+7 hours') AS end_time_h
    from 
        stream_table
    where msPlayed > 0
"""

print(psql(query))

                 end_ts    end_date end_time_hm end_time_h
0      2025-07-18 10:39  2025-07-18       17:39         17
1      2025-07-18 10:45  2025-07-18       17:45         17
2      2025-07-18 10:46  2025-07-18       17:46         17
3      2025-07-18 15:48  2025-07-18       22:48         22
4      2025-07-18 15:51  2025-07-18       22:51         22
...                 ...         ...         ...        ...
31802  2026-03-08 05:11  2026-03-08       12:11         12
31803  2026-03-08 05:13  2026-03-08       12:13         12
31804  2026-03-08 05:16  2026-03-08       12:16         12
31805  2026-03-08 05:19  2026-03-08       12:19         12
31806  2026-03-08 05:22  2026-03-08       12:22         12

[31807 rows x 4 columns]

# Creating tracks table

In [22]:
import json

FOLDER_METADATA = Path('/Users/qaulanmaruf/Desktop/alans_spotify_2025/spotify_account_data/metadata')

with open(FOLDER_METADATA / "YourLibrary.json") as f:
    data = json.load(f)

tracks_df = pd.json_normalize(data["tracks"])

In [23]:
display(tracks_df.head(10))

,artist,album,track,uri
0,Muse,Feeling Good / Hyper Music,Shine,spotify:track:0et8hkT6NB9slDSMulahDp
1,The Revivalists,Men Amongst Mountains,Wish I Knew You,spotify:track:7AOhUY89PYUxswAQax48ZB
2,Styx,Cornerstone,Boat On The River,spotify:track:4o9DSo7c1ICv4CtFWFSmGx
3,Queen,Hungarian Rhapsody,Friends Will Be Friends - Live,spotify:track:3UfnnpAoRpnwSoGPdpdWJh
4,Victor Hutabarat,Damai Sukacita Natal,Dari Pulau Dan Benua,spotify:track:4qHcFn29JTCQwOVsT4S63z
5,Vintonic,Semesta Asmara,Semesta Asmara,spotify:track:0tn3dQuEHJEhGlILenLYnM
6,Eelke Kleijn,Transmission,Transmission - Joris Voorn Remix,spotify:track:6ziqWx82jgkQYhyIALoraH
7,Queen,Queen Rock Montreal,Somebody To Love - Live,spotify:track:0DdWFXRHEyCzAGCVCsb9LK
8,Glee Cast,Glee: The Music presents The Warblers,Somewhere Only We Know (feat. Darren Criss) - ...,spotify:track:7qekEQyGFRim7qNhxzkaLo
9,Queen,Made In Heaven,I Was Born To Love You - 2011 Remaster,spotify:track:7DtdhIJlSSOaAFNk4JdXCb

In [24]:
query = """ 
    select * from tracks_df
"""

print(psql(query))

                 artist                       album  \
0                  Muse  Feeling Good / Hyper Music
1       The Revivalists       Men Amongst Mountains
2                  Styx                 Cornerstone
3                 Queen          Hungarian Rhapsody
4      Victor Hutabarat        Damai Sukacita Natal
..                  ...                         ...
574     Verka Serduchka                    Do Re Mi
575        Hippo Campus                    landmark
576   Killing Me Inside                  Selftitled
577         Disco Lines               No Broke Boys
578  Gilbert O'Sullivan                    Songbook

                                          track  \
0                                         Shine
1                               Wish I Knew You
2                             Boat On The River
3                Friends Will Be Friends - Live
4                          Dari Pulau Dan Benua
..                                          ...
574                        Dancing Lasha Tumbai
575                                 way it goes
576                                     Torment
577                               No Broke Boys
578  Happiness Is Me and You - Songbook Version

                                      uri
0    spotify:track:0et8hkT6NB9slDSMulahDp
1    spotify:track:7AOhUY89PYUxswAQax48ZB
2    spotify:track:4o9DSo7c1ICv4CtFWFSmGx
3    spotify:track:3UfnnpAoRpnwSoGPdpdWJh
4    spotify:track:4qHcFn29JTCQwOVsT4S63z
..                                    ...
574  spotify:track:3ve2mVR6BkXuNWfHVoA5yu
575  spotify:track:14qApXn4L9UI0jQozlq6st
576  spotify:track:6USgemtsfcRaqfcd1fpsFl
577  spotify:track:3cZajhyr8LmtPfHZ9296tj
578  spotify:track:1SU7YS19WuktePy16BhNS7

[579 rows x 4 columns]

In [25]:
artists_df = pd.json_normalize(data["artists"])

In [26]:
display(artists_df.head(10))

                name                                    uri
0             .Feast  spotify:artist:7Gy1PxqrgsiqWF6JNYPHeB
1            Beyoncé  spotify:artist:6vWDO969PvNqNYHIOW5v0m
2  Cage The Elephant  spotify:artist:26T3LtbuGT1Fu9m0eRq5X3
3             Ecco2k  spotify:artist:6hG0VsXXlD10l60TqiIHIX
4        Extremoduro  spotify:artist:3bgsNtcf5d5h9jbQbohfBK
5          Glee Cast  spotify:artist:0SCbttzoZTnLFebDYmAWCm
6     Gogol Bordello  spotify:artist:2SVw939fwuqSobLjF8u78b
7          Green Day  spotify:artist:7oPftvlwr6VrsViSDV7fJY
8              Hivi!  spotify:artist:4ubEZ6sMsrrbQChueyouCC
9              Keane  spotify:artist:53A0W3U0s8diEn9RhXQhVz

In [28]:
albums_df = pd.json_normalize(data["albums"])

In [30]:
display(albums_df.head(10))

,artist,album,uri
0,Aria,Легенды русского рока: Ария,spotify:album:3ke0AwigfXAH8duC7ZSD58
1,Sam Fender,Hypersonic Missiles,spotify:album:7FWCgfnTgupXdyBy51ME9m
2,Kino,Виктор Цой 55,spotify:album:7trila5XMOsUUkcujWqzcn
3,Green Day,American Idiot,spotify:album:19ObsGobUuBr11M6ysFMug
4,Jeff Rosenstock,WORRY.,spotify:album:18doqXfbCTpyz1PeO3d4eB
5,Barbra Streisand,Funny Girl - Original Soundtrack Recording,spotify:album:0G8qWYPobQUV9wDm2XABPp
6,Various Artists,Live 8,spotify:album:15t7NAV9KXOtPo7HefS39H
7,Kok Viral,Ganteng Review Saldonya Dong,spotify:album:1XV1pTaV33QP6RAa3hUtDq
8,André Rieu,The Sound of Heaven,spotify:album:5al1TnP3jdoRnRHmQ1BU16
9,Queen,Queen II,spotify:album:1HFobzrUk120xHeop7rC5D

# Creating ID identifier for unique artistName-trackName pairs